name: yutto-uiya
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pydantic>=2.10.6
      - tomli_w>=1.2.0
      - uiya-yutto==0.0.5
      - httpx[http2,socks]>=0.28.1
      - natsort>=8.4.0
