name: Lint Python

on:
  push:
    branches: [dev]
    paths:
      - "python/**"
      - "pyproject.toml"
      - "uv.lock"
      - "justfile"
      - ".github/workflows/lint-python.yml"
  pull_request:
    paths:
      - "python/**"
      - "pyproject.toml"
      - "uv.lock"
      - "justfile"
      - ".github/workflows/lint-python.yml"
  workflow_dispatch:

jobs:
  lint-and-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        architecture: ["x64"]
    name: Lint and Format
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: just ci-install

      - name: Lint
        run: just ci-lint-python

      - name: Format check
        run: just ci-fmt-check-python
